# Git Commit 禁止 AI 署名 Hook (PowerShell 版本)
# 自动检查并移除 AI 相关的署名信息

param($commitMsgFile)

if (-not $commitMsgFile) {
    $commitMsgFile = $args[0]
}

$commitMsg = Get-Content $commitMsgFile -Raw

# 检测 AI 署名的关键词模式
$aiPatterns = @(
    'Co-authored-by:.*Claude',
    'Co-authored-by:.*ChatGPT',
    'Co-authored-by:.*Copilot',
    'Co-authored-by:.*AI',
    'Generated by Claude',
    'Generated by ChatGPT',
    'Generated by AI',
    'With assistance from Claude',
    'With assistance from ChatGPT',
    'AI-assisted',
    'AI-generated',
    'Pair programmed with Claude',
    'Pair programmed with ChatGPT',
    'Claude Code',
    'Co-authored-by:.*claude',
    'Co-authored-by:.*copilot',
    'Cursor AI',
    'Codeium'
)

# 检查是否包含 AI 署名
$hasAiSignature = $false
$detectedSignatures = @()

foreach ($pattern in $aiPatterns) {
    if ($commitMsg -match $pattern) {
        $hasAiSignature = $true
        $matches = [regex]::Matches($commitMsg, $pattern)
        foreach ($match in $matches) {
            $detectedSignatures += $match.Value
        }
    }
}

if ($hasAiSignature) {
    Write-Host "❌ 错误: 提交信息包含 AI 署名" -ForegroundColor Red
    Write-Host ""
    Write-Host "检测到以下 AI 相关署名:" -ForegroundColor Yellow
    foreach ($sig in $detectedSignatures) {
        Write-Host "  - $sig" -ForegroundColor Yellow
    }
    Write-Host ""
    Write-Host "请移除 AI 署名后再提交。" -ForegroundColor Red
    Write-Host "提示: 使用 git commit --amend 修改提交信息" -ForegroundColor Cyan
    exit 1
}

# 自动清理常见的 AI 标记
$cleanedMsg = $commitMsg
foreach ($pattern in $aiPatterns) {
    $cleanedMsg = $cleanedMsg -replace "(?m)^.*$pattern.*`r?`n?", ""
}

# 清理多余的空行
$cleanedMsg = $cleanedMsg -replace "(`r?`n){3,}", "`r`n`r`n"
$cleanedMsg = $cleanedMsg.Trim()

# 如果清理后内容有变化，更新文件
if ($cleanedMsg -ne $commitMsg.Trim()) {
    $cleanedMsg | Out-File -FilePath $commitMsgFile -Encoding UTF8 -NoNewline
    Write-Host "✓ 已自动移除 AI 署名信息" -ForegroundColor Green
}

exit 0
